//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StajerDbEntities : DbContext
    {
        public StajerDbEntities()
            : base("name=StajerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bina> Bina { get; set; }
        public virtual DbSet<Misafirler> Misafirler { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Ad_Oda> Ad_Oda { get; set; }
        public virtual DbSet<KalinanOdaVw> KalinanOdaVw { get; set; }
        public virtual DbSet<viewolustur> viewolustur { get; set; }
    }
}
